"""
schemas.py — Pydantic models for the AI-generated learning roadmap.

These models faithfully mirror the JSON structure returned by Claude
(see ``learning_roadmap_generated by Claude.json`` at the project root).
Only the ``roadmap`` payload is modelled here; the outer Anthropic
message envelope is **not** included since it is an SDK implementation
detail.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

# ── Request ───────────────────────────────────────────────────────────────────


class RoadmapGenerateRequest(BaseModel):
    """Payload the client sends to ``POST /api/roadmap/generate``."""

    missing_skills: list[str] = Field(
        ...,
        min_length=1,
        description="Non-empty list of skills the user is missing.",
        examples=[["TypeScript", "Docker", "System Design"]],
    )
    jd_text: str | None = Field(
        default=None,
        description="Optional raw job-description text for extra context.",
    )


# ── Nested response models ───────────────────────────────────────────────────


class TimelinePhase(BaseModel):
    """A single phase inside the learning timeline."""

    phase: int
    title: str
    duration_weeks: int
    start_week: int
    end_week: int
    focus_skills: list[str]
    weekly_commitment_hours: int
    milestones: list[str]


class Course(BaseModel):
    """A single course recommendation."""

    title: str
    platform: str
    instructor: str
    level: str
    duration_hours: int
    url: str
    priority: str


class SkillCourses(BaseModel):
    """Courses grouped by the skill they target."""

    skill: str
    courses: list[Course]


class ProjectIdea(BaseModel):
    """A hands-on project suggestion linked to specific skills & phases."""

    id: str
    title: str
    description: str
    skills_practiced: list[str]
    difficulty: str
    estimated_hours: int
    phase: int
    deliverables: list[str]


class RoadmapSummary(BaseModel):
    """High-level aggregated stats for the entire roadmap."""

    total_courses: int
    total_projects: int
    total_learning_hours: int
    recommended_weekly_pace: str
    completion_target: str


class Roadmap(BaseModel):
    """Top-level roadmap payload generated by Claude."""

    generated_for: str | None = None
    generated_at: str | None = None
    missing_skills: list[str]
    total_estimated_duration_weeks: int
    timeline: list[TimelinePhase]
    course_recommendations: list[SkillCourses]
    project_ideas: list[ProjectIdea]
    summary: RoadmapSummary


# ── API response wrapper ─────────────────────────────────────────────────────


class RoadmapGenerateResponse(BaseModel):
    """Response body for ``POST /api/roadmap/generate``."""

    roadmap: Roadmap
